name: ethereum_util
description: a collection of utility functions for Ethereum
version: 2.0.0
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  pointycastle: ^3.0.1
  buffer: ^1.1.1
  equatable:
  collection: ^1.15.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner:
  json_serializable: ^6.1.4
  path:
  test:
